apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeploy
   labels:
      env: dev
spec:
   replicas: 2
   selector:
     matchLabels:
        name: pod
   strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1         
   template:
     metadata:
       name: cafe
       labels:
         name: pod
     spec:
       containers:
       - name: cafeimage
         image: rajujaat25/cafenewimage:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 80


