apiVersion: v1
kind: Service
metadata: 
  name: mysvc
  labels:
    env: svc
spec:
  selector:
    name: pod
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
